### ISSUE TITLE
Updating to 1.0.4 version

### ISSUE THREAD

**Issue by jhonpi** [paymentez/paymentez-ios#27]
I'm updating an old version of PaymentezSDK. I'm already build and update the PaymentzSDK library and it seems ok, but in this version the function to delete a card of the `PaymentezSDKClient` class is not accesible.
Is this function not available to be used?
How can I delete a card using your framework?

Thanks in advance

**Comment by titopalito** [comment]
Im not from Paymentez but i did it:

POST:
Headers:
"Content-Type" = "application/json"
"Auth-Token" = {your_auth_token}

Url: 
https://ccapi-stg.paymentez.com/v2/card/delete/

Make a Json with an array like this one:
[
  "card": ["token": "card-token"],
  "user": ["id": "UidUsuario"]
]

You will get a json response.

Best regards.

**Comment by titopalito** [comment]
Now my problem is that i cant build the proyect because of "missing moodule CommonCrypto"...
Tried to map it manually but didn't worked...
