### ISSUE TITLE
Error en IDE "missing module CommonCrypto"

### ISSUE THREAD

**Issue by titopalito** [paymentez/paymentez-ios#28]
Luego de seguir paso a paso la instalación de carthage y la configuración para agregar el framework.

al hacer el import en el appDelegate, el editor me retorna este error.

De momento estoy usando la version actual del xcode(9.2) y la ultima version de su framework.

**Comment by guxx** [comment]
Para la instalación de Carthage
es necesario incluir CommonCrypto aparte, debido a que ellos hacen la compilación usando sus parámetros. Puedes guiarte por este [link](https://stackoverflow.com/questions/25248598/importing-commoncrypto-in-a-swift-framework)
